# Generated by Django 5.0.6 on 2024-06-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='custom_url',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True),
        ),
    ]
