# Generated by Django 5.0.6 on 2024-06-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nome_empresa',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
