# Generated by Django 5.0.6 on 2024-06-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofile_nome_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
