# Generated by Django 5.0.6 on 2024-07-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_github_userprofile_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
